apiVersion: apps/v1
kind: Deployment
metadata:
  name: productdb
  labels:
    app: productdb
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: productdb
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: productdb
    spec:
      containers:
      - image: jaypark00/productdb:1.0
        imagePullPolicy: Always
        name: productdb
        ports:
        - containerPort: 3306
          protocol: TCP
