apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  selector:
    app: rabbitmq
  ports:
    - name: rabbitmq-port1
      protocol: TCP
      port: 5672
      targetPort: 5672
    - name: rabbitmq-port2
      protocol: TCP
      port: 15672
      targetPort: 15672
      
