apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
spec:
  selector:
    app: elasticsearch
  ports:
    - name: elasticsearch-port1
      protocol: TCP
      port: 9200
      targetPort: 9200
    - name: elasticsearch-port2
      protocol: TCP
      port: 9300
      targetPort: 9300
      
