apiVersion: apps/v1
kind: Deployment
metadata:
  name: configserver
  labels:
    app: configserver
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: configserver
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: configserver
    spec:
      containers:
      - image: jaypark00/configserver:1.0
        imagePullPolicy: Always
        name: configserver
        env:
        - name: GIT_URI
          value: https://github.com/jaypark00/jpetstore-config-repo.git
        - name: DEFAULT_BRANCH
          value: master
        ports:
        - containerPort: 8888
          protocol: TCP
