apiVersion: apps/v1
kind: Deployment
metadata:
  name: product
  labels:
    app: product
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
      - image: jaypark00/product:msa_v2
        imagePullPolicy: Always
        name: product
        env:
        - name: PROFILE
          value: prod
        - name: SPRING_CLOUD_CONFIG_URI
          value: http://configserver:8888
        - name: PRODUCT_PORT
          value: "17071"
        - name: DATASOURCE_URL
          value: jdbc:mariadb://productdb-msa:3306/productdb
        - name: DB_USERNAME
          value: product
        - name: DB_PASSWORD
          value: qwer1234
        - name: RABBITMQ_HOST
          value: rabbitmq
        - name: RABBITMQ_PORT
          value: "5672"
        - name: RABBITMQ_USERNAME
          value: jpetstore
        - name: RABBITMQ_PASSWORD
          value: qwer1234
        - name: EUREKA_DEFAULTZONE
          value: http://eurekaserver:8761/eureka/,http://eurekaserver2:8762/eureka/
        - name: ZIPKIN_URI
          value: http://zipkin:9411/
        - name: ELASTICSEARCH_HOSTS
          value: elasticsearch:9200
        - name: KIBANA_HOST
          value: kibana:5601
        ports:
        - containerPort: 17071
          protocol: TCP
