apiVersion: apps/v1
kind: Deployment
metadata:
  name: jpetstoredb
  labels:
    app: jpetstoredb
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jpetstoredb
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: jpetstoredb
    spec:
      containers:
      - image: jaypark00/jpetstoredb:1.0
        imagePullPolicy: Always
        name: jpetstoredb
        ports:
        - containerPort: 3306
          protocol: TCP
