apiVersion: apps/v1
kind: Deployment
metadata:
  name: zuulserver
  labels:
    app: zuulserver
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: zuulserver
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: zuulserver
    spec:
      containers:
      - image: jaypark00/zuulserver:msa_v2
        imagePullPolicy: Always
        name: zuulserver
        env:
        - name: PROFILE
          value: prod
        - name: SPRING_CLOUD_CONFIG_URI
          value: http://configserver:8888
        - name: ZUUL_PORT
          value: "8080"
        - name: EUREKA_DEFAULTZONE
          value: http://eurekaserver:8761/eureka/,http://eurekaserver2:8762/eureka/
        - name: ZIPKIN_URI
          value: http://zipkin:9411/
        - name: ELASTICSEARCH_HOSTS
          value: elasticsearch:9200
        - name: KIBANA_HOST
          value: kibana:5601
        ports:
        - containerPort: 8080
          protocol: TCP
