apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: zuulserver
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: zuulserver
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 70