apiVersion: apps/v1
kind: Deployment
metadata:
  name: eurekaserver
  labels:
    app: eurekaserver
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eurekaserver
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: eurekaserver
    spec:
      containers:
      - image: jaypark00/eurekaserver:1.0
        imagePullPolicy: Always
        name: eurekaserver
        env:
        - name: PROFILE
          value: prod
        - name: SPRING_CLOUD_CONFIG_URI
          value: http://configserver:8888
        - name: EUREKA_PORT
          value: "8761"
        - name: OTHER_EUREKA_URI
          value: eurekaserver2:8762
        ports:
        - containerPort: 8761
          protocol: TCP
