apiVersion: apps/v1
kind: Deployment
metadata:
  name: eurekaserver2
  labels:
    app: eurekaserver2
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eurekaserver2
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: eurekaserver2
    spec:
      containers:
      - image: jaypark00/eurekaserver:msa_v1
        imagePullPolicy: Always
        name: eurekaserver2
        env:
        - name: PROFILE
          value: prod
        - name: SPRING_CLOUD_CONFIG_URI
          value: http://configserver:8888
        - name: EUREKA_PORT
          value: "8762"
        - name: OTHER_EUREKA_URI
          value: eurekaserver:8761
        ports:
        - containerPort: 8762
          protocol: TCP
