apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderdb
  labels:
    app: orderdb
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orderdb
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: orderdb
    spec:
      containers:
      - image: jaypark00/orderdb:1.0
        imagePullPolicy: Always
        name: orderdb
        ports:
        - containerPort: 3306
          protocol: TCP
