apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: jpetstore
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: jpetstore
  minReplicas: 1
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70
