apiVersion: apps/v1
kind: Deployment
metadata:
  name: scouterserver
  labels:
    app: scouterserver
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scouterserver
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: scouterserver
    spec:
      containers:
      - image: jaypark00/scouterserver:1.0
        imagePullPolicy: Always
        name: scouterserver
        ports:
        - containerPort: 6100
          protocol: TCP
        - containerPort: 6100
          protocol: UDP
          