apiVersion: v1
kind: Service
metadata:
  name: scouterserver
spec:
  selector:
    app: scouterserver
  ports:
    - name: scouterserver-port1
      protocol: UDP
      port: 6100
      targetPort: 6100
    - name: scouterserver-port2
      protocol: TCP
      port: 6100
      targetPort: 6100