apiVersion: v1
kind: Service
metadata:
  name: scouterserver2
spec:
  selector:
    app: scouterserver
  ports:
    - name: scouterserver-port2
      protocol: UDP
      port: 6100
      targetPort: 6100
