apiVersion: v1
kind: Service
metadata:
  name: scouterserver-public
spec:
  selector:
    app: scouterserver
  type: LoadBalancer
  ports:
    - name: scouterserver-port-public
      protocol: TCP
      port: 6100
      targetPort: 6100